dubbo:
  application:
    name: boot-provider
  registry:
    address: 192.168.162.225:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20881
  monitor:
    protocol: registry
server:
  port: 8081